# docker-compose.yaml

version: '3'
services:
    gateway:
      build: gateway
      ports:
          - "5001:5001"
    auth:
      build: auth
      ports:
          - "5002:5002"
    
    db:
      image: mysql
      container_name: jobs_map-db-1
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=1
    
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: jobs_map-rabbitmq-1
      ports:
          - "15672:15672"
    
    scraper:
      build: scraper
      depends_on:
        - db
      ports:
          - "5003:5003"
    
    job_server:
      build: job_server
      depends_on:
        - scraper
      ports:
          - "5004:5004"
    
    llm_server:
      build: llm_server
      depends_on:
        - job_server
      ports:
          - "5005:5005"

    